title: Robbie Antenesse
email: dev@alamantus.com
description: Web Developer - Game Developer - Fun Haver
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://robbie.antenesse.net" # the base hostname & protocol for your site

collections:
  projects:
    output: true
  ideas:
    output: true