# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Robbie Antenesse
email: dev@alamantus.com
description: > # this means to ignore newlines until "baseurl:"
  Web Developer - Game Developer - Fun Haver
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://robbie.antenesse.net" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
twitter_username: Alamantus
github_username:  Alamantus
itchio_username: Alamantus
#facebook_username: Alamantus
#instagram_username: beyonce
#stackoverflow_url: https://
#googleplus_username: BobMarley
#skype_username: echo123
linkedin_url: https://www.linkedin.com/in/robbie-antenesse-68816371
mastodon_username: Alamantus
mastodon_node: cybre.space
mastodon_protocol: https://

# Address information
address_city: Denver
address_state: CO

collections:
- projects

# Build settings
markdown: kramdown
